### ISSUE TITLE
svg-sprite does not work with the components flag

### ISSUE THREAD

**Issue by fweinaug** [kiliman/rmx-cli#17]
great tool! i would like to generate a component for every sprite using the components flag. unfortunately it throws the following error:

```
Error: ENAMETOOLONG: name too long, open 'packages/design-system/src/icons/icon.tsx
export const AddIcon = (props: SVGProps<SVGSVGElement>) => <Icon icon="add" {...props} />;
export const AddressIcon = (props: SVGProps<SVGSVGElement>) => <Icon icon="address" {...props} />;
export const Appointment_canceledIcon = (props: SVGProps<SVGSVGElement>) => <Icon icon="appointment_canceled" {...props} />;'
    at Object.openSync (node:fs:590:3)
    at Object.writeFileSync (node:fs:2202:35)
    at generateReactComponent (/Users/florian/Source/design-system/node_modules/.pnpm/rmx-cli@0.4.13/node_modules/rmx-cli/dist/commands/svg-sprite.js:211:8)
    at generateSprite (/Users/florian/Source/design-system/node_modules/.pnpm/rmx-cli@0.4.13/node_modules/rmx-cli/dist/commands/svg-sprite.js:144:3)
    at generateSprites (/Users/florian/Source/design-system/node_modules/.pnpm/rmx-cli@0.4.13/node_modules/rmx-cli/dist/commands/svg-sprite.js:110:5)
    at Object.svg_sprite_default (/Users/florian/Source/design-system/node_modules/.pnpm/rmx-cli@0.4.13/node_modules/rmx-cli/dist/commands/svg-sprite.js:80:3)
    at main (/Users/florian/Source/design-system/node_modules/.pnpm/rmx-cli@0.4.13/node_modules/rmx-cli/dist/cli.js:34:24) {
  errno: -63,
  syscall: 'open',
  code: 'ENAMETOOLONG',
  path: 'packages/design-system/src/icons2/icon.tsx\n' +
    'export const AddIcon = (props: SVGProps<SVGSVGElement>) => <Icon icon="add" {...props} />;\n' +
    'export const AddressIcon = (props: SVGProps<SVGSVGElement>) => <Icon icon="address" {...props} />;\n' +
    'export const Appointment_canceledIcon = (props: SVGProps<SVGSVGElement>) => <Icon icon="appointment_canceled" {...props} />;\n' +

... (truncated to make it easier)
 ```

Looking at the code, the generated code for every component is added to the `component` variable (line 227-228) which is then  joined with `spriteOutputFolder` (line 231). correct would be the `output` variable.

---

**another very small change request related to this:**
the regex to generate the component name does not include underscores, only dashes, so the result is e.g. Appointment_canceledIcon. i think it would make sense to support that as well.

---

if you want i can create a PR.

**Comment by kiliman** [comment]
Thanks for trying it out. Yes please add a PR.

**Comment by fweinaug** [comment]
@kiliman i noticed that the generated icon components assume that the Icon component has a `icon` prop and they only provide the SVG element props. this does not work well when using a template.

1. one solution could be this, but it still assumes the component name and icon prop name:
```
      output += `
export const ${componentName}Icon = (props: Omit<React.ComponentProps<typeof Icon>, 'icon'>) => <Icon icon="${icon}" {...props} />;`
```

2. a better solution, but with more effort, could be to allow a template also for the generated components.

the first solution would solve my use case. what do you think?

**Comment by kiliman** [comment]
Fixed in v0.4.14

**Comment by fweinaug** [comment]
@kiliman thanks for merging and the new release! how do you see the topic from my previous comment? can also move it to a new issue

**Comment by kiliman** [comment]
Are you referring to this?

> 2. a better solution, but with more effort, could be to allow a template also for the generated components.

You can pass in a template file using the `--template=PATH` arg

Here's a sample template that was used by Epic Stack
```ts
// svg-icon-template.tsx

import { type SVGProps } from 'react'
import { cn } from '~/utils/misc.ts'
import href from './icon.svg'
export { href }

const sizeClassName = {
  font: 'w-[1em] h-[1em]',
  xs: 'w-3 h-3',
  sm: 'w-4 h-4',
  md: 'w-5 h-5',
  lg: 'w-6 h-6',
  xl: 'w-7 h-7',
} as const

type Size = keyof typeof sizeClassName

const childrenSizeClassName = {
  font: 'gap-1',
  xs: 'gap-1',
  sm: 'gap-1',
  md: 'gap-2',
  lg: 'gap-2',
  xl: 'gap-3',
} satisfies Record<Size, string>

/**
 * Renders an SVG icon. The icon defaults to the size of the font. To make it
 * align vertically with neighboring text, you need to wrap the icon and text
 * in a common parent and set the parent to display "flex" (or "inline-flex").
 * Alternatively, if you're ok with the icon being to the left of the text,
 * you can pass the text as a child of the icon and it will be automatically
 * aligned.
 */
export function Icon({
  name,
  size = 'font',
  className,
  children,
  ...props
}: SVGProps<SVGSVGElement> & {
  name: IconName
  size?: Size
}) {
  if (children) {
    return (
      <span className={`inline-flex ${childrenSizeClassName[size]}`}>
        <Icon name={name} size={size} className={className} {...props} />
        {children}
      </span>
    )
  }
  return (
    <svg
      {...props}
      className={cn(sizeClassName[size], 'inline self-center', className)}
    >
      <use href={`${href}#${name}`} />
    </svg>
  )
}
```

**Comment by fweinaug** [comment]
i created a new issue #21 since this a new topic :)
